CREATE TABLE HECHOS
(   FECHA_KEY			NUMBER(8,0),
    HORA_OCURRENCIA_KEY		NUMBER(3,0),
    G_HORA_KEY		        NUMBER(3,0),
    G_HORA_5_KEY		NUMBER(3,0),
    DEPARTAMENTO_KEY		NUMBER(3,0),
    MUNICIPIO_KEY		NUMBER(4,0),		
    ZONA_OCURRENCIA_KEY		NUMBER(4,0),
    GENERO_KEY    	        NUMBER(1,0),		
    EDAD_PERSONA_KEY		NUMBER(3,0),
    G_EDAD_80_MAS_KEY		NUMBER(3,0),
    G_EDAD_60_MAS_KEY		NUMBER(3,0),
    EDAD_QUINCENAL_KEY		NUMBER(3,0),
    MAYOR_MENOR_KEY		NUMBER(1,0),
    TIPO_VEHICULO_KEY		NUMBER(2,0),
    MARCA_VEHICULO_KEY		NUMBER(3,0),
    COLOR_VEHICULO_KEY		NUMBER(3,0),
    MODELO_VEHICULO_KEY		NUMBER(4,0),
    G_MODELO_VEHICULO_KEY	NUMBER(2,0),
    TIPO_EVENTO_KEY		NUMBER(2,0),
    FALLECIDO_LESIONADO_KEY	NUMBER(1,0),
    INTERNADO_KEY		NUMBER(1,0),
    CANTIDAD_PERSONAS		NUMBER(8,0),	
    GTOS_CALC_PER		NUMBER(10,2),	
    GTOS_CALC_BIE		NUMBER(10,2)
);

CREATE TABLE NO_HECHOS
(   FECHA			    DATE,
    FECHA_KEY			NUMBER(8,0),
    HORA_OCURRENCIA		NUMBER(3,0),
    HORA_OCURRENCIA_KEY		NUMBER(3,0),
    G_HORA			NUMBER(3,0),
    G_HORA_KEY		        NUMBER(3,0),
    G_HORA_5			NUMBER(3,0),
    G_HORA_5_KEY		NUMBER(3,0),
    DEPARTAMENTO		NUMBER(3,0),
    DEPARTAMENTO_KEY		NUMBER(3,0),
    MUNICIPIO			NUMBER(4,0),		
    MUNICIPIO_KEY		NUMBER(4,0),		
    ZONA_OCURRENCIA		NUMBER(4,0),
    ZONA_OCURRENCIA_KEY		NUMBER(4,0),
    GENERO			NUMBER(1,0),		
    GENERO_KEY    	        NUMBER(1,0),		
    EDAD_PERSONA		NUMBER(3,0),
    EDAD_PERSONA_KEY		NUMBER(3,0),
    G_EDAD_80_MAS		NUMBER(3,0),
    G_EDAD_80_MAS_KEY		NUMBER(3,0),
    G_EDAD_60_MAS		NUMBER(3,0),
    G_EDAD_60_MAS_KEY		NUMBER(3,0),
    EDAD_QUINCENAL		NUMBER(3,0),
    EDAD_QUINCENAL_KEY		NUMBER(3,0),
    MAYOR_MENOR			NUMBER(1,0),
    MAYOR_MENOR_KEY		NUMBER(1,0),
    TIPO_VEHICULO		NUMBER(2,0),
    TIPO_VEHICULO_KEY		NUMBER(2,0),
    MARCA_VEHICULO		NUMBER(3,0),
    MARCA_VEHICULO_KEY		NUMBER(3,0),
    COLOR_VEHICULO		NUMBER(3,0),
    COLOR_VEHICULO_KEY		NUMBER(3,0),
    MODELO_VEHICULO		NUMBER(4,0),
    MODELO_VEHICULO_KEY		NUMBER(4,0),
    G_MODELO_VEHICULO		NUMBER(2,0),
    G_MODELO_VEHICULO_KEY	NUMBER(2,0),
    TIPO_EVENTO			NUMBER(2,0),
    TIPO_EVENTO_KEY		NUMBER(2,0),
    FALLECIDO_LESIONADO		NUMBER(1,0),
    FALLECIDO_LESIONADO_KEY	NUMBER(1,0),
    INTERNADO			NUMBER(1,0),
    INTERNADO_KEY		NUMBER(1,0),
    CANTIDAD_PERSONAS		NUMBER(8,0),	
    GTOS_CALC_PER		NUMBER(10,2),	
    GTOS_CALC_BIE		NUMBER(10,2)
);

CREATE TABLE DIM_CAT_HORA_OCURRENCIA
(   
	HORA_KEY	   	NUMBER(3,0),
	HORA_COD	   	NUMBER(3,0),
	DSC_HORA_OCURRENCIA	VARCHAR2(50)
);

CREATE TABLE DIM_CAT_G_HORA
(   
	G_HORA_KEY		NUMBER(3,0),
	G_HORA_COD		NUMBER(3,0),
	DSC_G_HORA_OCURRENCIA	VARCHAR2(50)
);

CREATE TABLE DIM_CAT_G_HORA_5
(   
	G_HORA_5_KEY	NUMBER(3,0),
	G_HORA_5_COD	NUMBER(3,0),
	DSC_G_HORA_5	VARCHAR2(50)
);

CREATE TABLE DIM_CAT_DEPARTAMENTO
(   
	DEPARTAMENTO_KEY	NUMBER(3,0),
	DEPARTAMENTO_COD	NUMBER(3,0),
	DSC_DEPARTAMENTO	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_MUNICIPIO
(   
	MUNICIPIO_KEY	NUMBER(4,0),
	MUNICIPIO_COD	NUMBER(4,0),
	DSC_MUNICIPIO	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_ZONA
(   
	ZONA_KEY	NUMBER(4,0),
	ZONA_COD	NUMBER(4,0),
	DSC_ZONA	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_GENERO
(   
	GENERO_KEY	NUMBER(1,0),
	GENERO_COD	NUMBER(1,0),
	DSC_GENERO	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_EDAD
(   
	EDAD_KEY	NUMBER(3,0),
	EDAD_COD	NUMBER(3,0),
	DSC_EDAD	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_G_EDAD_80_MAS
(   
	G_EDAD_80_MAS_KEY	NUMBER(3,0),
	G_EDAD_80_MAS_COD   	NUMBER(3,0),
	DSC_G_EDAD_80_MAS  	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_G_EDAD_60_MAS
(   
	G_EDAD_60_MAS_KEY   	NUMBER(3,0),
	G_EDAD_60_MAS_COD   	NUMBER(3,0),
	DSC_G_EDAD_60_MAS  	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_EDAD_QUINCENAL
(   
	EDAD_QUINCENAL_KEY   NUMBER(3,0),
	EDAD_QUINCENAL_COD   NUMBER(3,0),
	DSC_EDAD_QUINCENAL  	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_MAYOR_MENOR
(   
	MAYOR_MENOR_KEY   	NUMBER(1,0),
	MAYOR_MENOR_COD   	NUMBER(1,0),
	DSC_MAYOR_MENOR  	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_TIPO_VEHICULO
(   
	TIPO_VEHICULO_KEY   NUMBER(2,0),
	TIPO_VEHICULO_COD   NUMBER(2,0),
	DSC_TIPO_VEHICULO  	VARCHAR2(100)
);

CREATE TABLE DIM_CAT_MARCA_VEHICULO
(   
	MARCA_VEHICULO_KEY  NUMBER(3,0),
	MARCA_VEHICULO_COD  NUMBER(3,0),
	DSC_MARCA_VEHICULO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_COLOR_VEHICULO
(   
	COLOR_VEHICULO_KEY  NUMBER(3,0),
	COLOR_VEHICULO_COD  NUMBER(3,0),
	DSC_COLOR_VEHICULO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_MODELO_VEHICULO
(   
	MODELO_VEHICULO_KEY  NUMBER(4,0),
	MODELO_VEHICULO_COD  NUMBER(4,0),
	DSC_MODELO_VEHICULO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_G_MODELO_VEHICULO
(   
	G_MODELO_VEHICULO_KEY  NUMBER(2,0),
	G_MODELO_VEHICULO_COD  NUMBER(2,0),
	DSC_G_MODELO_VEHICULO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_TIPO_EVENTO
(   
	TIPO_EVENTO_KEY  NUMBER(2,0),
	TIPO_EVENTO_COD  NUMBER(2,0),
	DSC_TIPO_EVENTO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_FALLECIDO_LESIONADO
(   
	FALLECIDO_LESIONADO_KEY  NUMBER(1,0),
	FALLECIDO_LESIONADO_COD  NUMBER(1,0),
	DSC_FALLECIDO_LESIONADO VARCHAR2(100)
);

CREATE TABLE DIM_CAT_INTERNADO
(   
	INTERNADO_KEY  NUMBER(1,0),
	INTERNADO_COD  NUMBER(1,0),
	DSC_INTERNADO VARCHAR2(100)
);

CREATE TABLE VALORES_DEFAULT
(
    NOMBRE_METRICA        VARCHAR2(50),
    VALOR                 NUMBER(8,0) 
);

CREATE TABLE REPROCESA_DIMENSIONES_QA
(
    NOMBRE_DIMENSION      VARCHAR2(50),
    FECHA                 DATE,
    PARAMETRO		  NUMBER(8,0) 
);

CREATE TABLE CONTROL_NUMERACION
(
    NOMBRE_DIMENSION      VARCHAR2(50),
    VALOR                 NUMBER(4,0) 
);

CREATE TABLE DIM_TIEMPO 
(
	FECHA_KEY NUMBER(8,0) NOT NULL,
	FECHA date NOT NULL,
	ANIO NUMBER(4,0) NOT NULL,
	MES NUMBER(2,0) NOT NULL,
	NOMBRE_MES VARCHAR2(15) NOT NULL,
	DIA NUMBER(2,0) NOT NULL,
	DIA_SEMANA NUMBER(1,0) NOT NULL,
	NOMBRE_DIA VARCHAR2(10) NOT NULL,
	SEMANA NUMBER(2,0) NOT NULL,
	SEMESTRE NUMBER(1,0) NOT NULL,
	NOMBRE_SEMESTRE VARCHAR2(25) NOT NULL,
	CUATRIMESTRE NUMBER(1,0) NOT NULL,
	NOMBRE_CUATRIMESTRE VARCHAR2(25) NOT NULL,
	TRIMESTRE NUMBER(1,0) NOT NULL,
	NOMBRE_TRIMESTRE VARCHAR2(25) NOT NULL,
	FECHA_SEMANA VARCHAR2(25) NULL
 );
 
 ----------------------------------------------------------------------
 --PROCEDIMIENTO
 ----------------------------------------------------------------------
 
 CREATE OR REPLACE PROCEDURE PRC_DEVUELVE_CORRELATIVOS (TABLA IN VARCHAR2, N OUT NUMBER)
AS
    V_FLAG NUMBER;
    NUMERO NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_FLAG FROM USER_TABLES WHERE TABLE_NAME = TABLA;
    
    IF V_FLAG = 0 THEN
        INSERT INTO CONTROL_NUMERACION VALUES (TABLA,1);
    ELSE
        SELECT COUNT(VALOR) INTO NUMERO FROM CONTROL_NUMERACION WHERE NOMBRE_DIMENSION = TABLA;
        
        IF NUMERO = 0 THEN
            INSERT INTO CONTROL_NUMERACION VALUES (TABLA,1);
            N := 1;
        ELSE
            SELECT VALOR INTO NUMERO FROM CONTROL_NUMERACION WHERE NOMBRE_DIMENSION = TABLA;
            NUMERO := NUMERO + 1;
            UPDATE CONTROL_NUMERACION SET VALOR = NUMERO WHERE NOMBRE_DIMENSION = TABLA;
            N := NUMERO;
        END IF;
    END IF;

END;

---------------
DECLARE
    S NUMBER;
BEGIN 
    PRC_DEVUELVE_CORRELATIVOS ('VALORES_DEFAULTT', S);
    DBMS_OUTPUT.PUT_LINE(S);
END;

--------------
SELECT * FROM NO_HECHOS
SELECT * FROM CONTROL_NUMERACION;