CREATE TABLE TRANSACCION
(   CORRELATIVO         NUMBER(8,0),
    FECHA		DATE,
    HORA_OCURRENCIA	NUMBER(3,0),
    G_HORA		NUMBER(3,0),
    G_HORA_5			NUMBER(3,0),
    DEPARTAMENTO		NUMBER(3,0),
    MUNICIPIO			NUMBER(4,0),		
    ZONA_OCURRENCIA		NUMBER(4,0),
    GENERO			    NUMBER(1,0),		
    EDAD_PERSONA		NUMBER(3,0),
    G_EDAD_80_MAS		NUMBER(3,0),
    G_EDAD_60_MAS		NUMBER(3,0),
    EDAD_QUINCENAL		NUMBER(3,0),
    MAYOR_MENOR			NUMBER(1,0),
    TIPO_VEHICULO		NUMBER(2,0),
    MARCA_VEHICULO		NUMBER(3,0),
    COLOR_VEHICULO		NUMBER(3,0),
    MODELO_VEHICULO		NUMBER(4,0),
    G_MODELO_VEHICULO	NUMBER(2,0),
    TIPO_EVENTO			NUMBER(2,0),
    FALLECIDO_LESIONADO	NUMBER(1,0),
    INTERNADO			NUMBER(1,0),
    CANTIDAD_PERSONAS	NUMBER(8,0),	
    GTOS_CALC_PER		NUMBER(10,2),	
    GTOS_CALC_BIE		NUMBER(10,2)
);

CREATE TABLE CAT_HORA_OCURRENCIA
(   
	ID_HORA			   	NUMBER(3,0),
	DSC_HORA_OCURRENCIA	VARCHAR2(50)
);

CREATE TABLE CAT_G_HORA
(   
	ID_G_HORA		   		NUMBER(3,0),
	DSC_G_HORA_OCURRENCIA	VARCHAR2(50)
);

CREATE TABLE CAT_G_HORA_5
(   
	ID_G_HORA_5		NUMBER(3,0),
	DSC_G_HORA_5	VARCHAR2(50)
);

CREATE TABLE CAT_DEPARTAMENTO
(   
	ID_DEPARTAMENTO		NUMBER(3,0),
	DSC_DEPARTAMENTO	VARCHAR2(100)
);

CREATE TABLE CAT_MUNICIPIO
(   
	ID_MUNICIPIO	NUMBER(4,0),
	DSC_MUNICIPIO	VARCHAR2(100)
);

CREATE TABLE CAT_ZONA
(   
	ID_ZONA		NUMBER(4,0),
	DSC_ZONA	VARCHAR2(100)
);

CREATE TABLE CAT_GENERO
(   
	ID_GENERO	NUMBER(1,0),
	DSC_GENERO	VARCHAR2(100)
);

CREATE TABLE CAT_EDAD
(   
	ID_EDAD		NUMBER(3,0),
	DSC_EDAD	VARCHAR2(100)
);

CREATE TABLE CAT_G_EDAD_80_MAS
(   
	ID_G_EDAD_80_MAS   NUMBER(3,0),
	DSC_G_EDAD_80_MAS  VARCHAR2(100)
);

CREATE TABLE CAT_G_EDAD_60_MAS
(   
	ID_G_EDAD_60_MAS   NUMBER(3,0),
	DSC_G_EDAD_60_MAS  VARCHAR2(100)
);

CREATE TABLE CAT_EDAD_QUINCENAL
(   
	ID_EDAD_QUINCENAL   NUMBER(3,0),
	DSC_EDAD_QUINCENAL  VARCHAR2(100)
);

CREATE TABLE CAT_MAYOR_MENOR
(   
	ID_MAYOR_MENOR   NUMBER(1,0),
	DSC_MAYOR_MENOR  VARCHAR2(100)
);

CREATE TABLE CAT_TIPO_VEHICULO
(   
	ID_TIPO_VEHICULO   NUMBER(2,0),
	DSC_TIPO_VEHICULO  VARCHAR2(100)
);

CREATE TABLE CAT_MARCA_VEHICULO
(   
	ID_MARCA_VEHICULO  NUMBER(3,0),
	DSC_MARCA_VEHICULO VARCHAR2(100)
);

CREATE TABLE CAT_COLOR_VEHICULO
(   
	ID_COLOR_VEHICULO  NUMBER(3,0),
	DSC_COLOR_VEHICULO VARCHAR2(100)
);

CREATE TABLE CAT_MODELO_VEHICULO
(   
	ID_MODELO_VEHICULO  NUMBER(4,0),
	DSC_MODELO_VEHICULO VARCHAR2(100)
);

CREATE TABLE CAT_G_MODELO_VEHICULO
(   
	ID_G_MODELO_VEHICULO  NUMBER(2,0),
	DSC_G_MODELO_VEHICULO VARCHAR2(100)
);

CREATE TABLE CAT_TIPO_EVENTO
(   
	ID_TIPO_EVENTO  NUMBER(2,0),
	DSC_TIPO_EVENTO VARCHAR2(100)
);

CREATE TABLE CAT_FALLECIDO_LESIONADO
(   
	ID_FALLECIDO_LESIONADO  NUMBER(1,0),
	DSC_FALLECIDO_LESIONADO VARCHAR2(100)
);

CREATE TABLE CAT_INTERNADO
(   
	ID_INTERNADO  NUMBER(1,0),
	DSC_INTERNADO VARCHAR2(100)
);

CREATE TABLE WATERMARK
(   
	TABLA  VARCHAR2(30),
	PK	   NUMBER(6,0),
	OPERACION VARCHAR2(1),
	FECHA_INSERT DATE,
	MIGRO VARCHAR2(1) DEFAULT 'N',
	FECHA_OPERADO DATE
);

-----------------------




--CAT_HORA_OCURRENCIA
INSERT INTO CAT_HORA_OCURRENCIA VALUES (0,'CERO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (1,'UNA');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (2,'DOS');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (3,'TRES');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (4,'CUATRO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (5,'CINCO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (6,'SEIS');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (7,'SIETE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (8,'OCHO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (9,'NUEVE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (10,'DIEZ');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (11,'ONCE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (12,'DOCE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (13,'TRECE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (14,'CATORCE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (15,'QUINCE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (16,'DIECISEIS');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (17,'DIECISIETE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (18,'DIECIOCHO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (19,'DIECINUEVE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (20,'VEINTE');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (21,'VEINTIUNO');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (22,'VEINTIDOS');
INSERT INTO CAT_HORA_OCURRENCIA VALUES (23,'VEINTITRES');

-- CAT_G_HORA
INSERT INTO CAT_G_HORA VALUES (1,'De 00:00 a 05:59');
INSERT INTO CAT_G_HORA VALUES (2,'De 06:00 a 11:59');
INSERT INTO CAT_G_HORA VALUES (3,'De 12:00 a 17:59');
INSERT INTO CAT_G_HORA VALUES (4,'De 18:00 a 23:59');
INSERT INTO CAT_G_HORA VALUES (99,'SIN REGISTRO');

-- CAT_G_HORA_5
INSERT INTO CAT_G_HORA_5 VALUES (1,'MAÑANA');
INSERT INTO CAT_G_HORA_5 VALUES (2,'TARDE');
INSERT INTO CAT_G_HORA_5 VALUES (3,'NOCHE');
INSERT INTO CAT_G_HORA_5 VALUES (4,'SIN REGISTRO');

-- CAT_DEPARTAMENTO
INSERT INTO CAT_DEPARTAMENTO VALUES (1,'Guatemala');
INSERT INTO CAT_DEPARTAMENTO VALUES (2,'El Progreso');
INSERT INTO CAT_DEPARTAMENTO VALUES (3,'Sacatepéquez');
INSERT INTO CAT_DEPARTAMENTO VALUES (4,'Chimaltenango');
INSERT INTO CAT_DEPARTAMENTO VALUES (5,'Escuintla');
INSERT INTO CAT_DEPARTAMENTO VALUES (6,'Santa Rosa');
INSERT INTO CAT_DEPARTAMENTO VALUES (7,'Sololá');
INSERT INTO CAT_DEPARTAMENTO VALUES (8,'Totonicapán');
INSERT INTO CAT_DEPARTAMENTO VALUES (9,'Quetzaltenango');
INSERT INTO CAT_DEPARTAMENTO VALUES (10,'Suchitepéquez');
INSERT INTO CAT_DEPARTAMENTO VALUES (11,'Retalhuleu');
INSERT INTO CAT_DEPARTAMENTO VALUES (12,'San Marcos');
INSERT INTO CAT_DEPARTAMENTO VALUES (13,'Huehuetenango');
INSERT INTO CAT_DEPARTAMENTO VALUES (14,'Quiché');
INSERT INTO CAT_DEPARTAMENTO VALUES (15,'Baja Verapaz');
INSERT INTO CAT_DEPARTAMENTO VALUES (16,'Alta Verapaz');
INSERT INTO CAT_DEPARTAMENTO VALUES (17,'Petén');
INSERT INTO CAT_DEPARTAMENTO VALUES (18,'Izabal');
INSERT INTO CAT_DEPARTAMENTO VALUES (19,'Zacapa');
INSERT INTO CAT_DEPARTAMENTO VALUES (20,'Chiquimula');
INSERT INTO CAT_DEPARTAMENTO VALUES (21,'Jalapa');
INSERT INTO CAT_DEPARTAMENTO VALUES (22,'Jutiapa');

-- CAT_MUNICIPIO
INSERT INTO CAT_MUNICIPIO VALUES (101,'Guatemala ');
INSERT INTO CAT_MUNICIPIO VALUES (102,'Santa Catarina Pinula ');
INSERT INTO CAT_MUNICIPIO VALUES (103,'San José Pinula');
INSERT INTO CAT_MUNICIPIO VALUES (104,'San José del Golfo');
INSERT INTO CAT_MUNICIPIO VALUES (105,'Palencia');
INSERT INTO CAT_MUNICIPIO VALUES (106,'Chinautla');
INSERT INTO CAT_MUNICIPIO VALUES (107,'San Pedro Ayampuc');
INSERT INTO CAT_MUNICIPIO VALUES (108,'Mixco');
INSERT INTO CAT_MUNICIPIO VALUES (109,'San Pedro Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (110,'San Juan Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (111,'San Raymundo');
INSERT INTO CAT_MUNICIPIO VALUES (112,'Chuarrancho');
INSERT INTO CAT_MUNICIPIO VALUES (113,'Fraijanes');
INSERT INTO CAT_MUNICIPIO VALUES (114,'Amatitlán');
INSERT INTO CAT_MUNICIPIO VALUES (115,'Villa Nueva');
INSERT INTO CAT_MUNICIPIO VALUES (116,'Villa Canales');
INSERT INTO CAT_MUNICIPIO VALUES (117,'Petapa ');
INSERT INTO CAT_MUNICIPIO VALUES (201,'Guastatoya');
INSERT INTO CAT_MUNICIPIO VALUES (202,'Morazán');
INSERT INTO CAT_MUNICIPIO VALUES (203,'San Agustín Acasaguastlán');
INSERT INTO CAT_MUNICIPIO VALUES (204,'San Cristóbal Acasaguastlán ');
INSERT INTO CAT_MUNICIPIO VALUES (205,'El Jícaro');
INSERT INTO CAT_MUNICIPIO VALUES (206,'Sansare');
INSERT INTO CAT_MUNICIPIO VALUES (207,'Sanarate');
INSERT INTO CAT_MUNICIPIO VALUES (208,'San Antonio la Paz');
INSERT INTO CAT_MUNICIPIO VALUES (301,'Antigua Guatemala');
INSERT INTO CAT_MUNICIPIO VALUES (302,'Jocotenango');
INSERT INTO CAT_MUNICIPIO VALUES (303,'Pastores');
INSERT INTO CAT_MUNICIPIO VALUES (304,'Sumpango');
INSERT INTO CAT_MUNICIPIO VALUES (305,'Santo Domingo Xenacoj');
INSERT INTO CAT_MUNICIPIO VALUES (306,'Santiago Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (307,'San Bartolomé Milpas Altas');
INSERT INTO CAT_MUNICIPIO VALUES (308,'San Lucas Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (309,'Santa Lucía Milpas Altas');
INSERT INTO CAT_MUNICIPIO VALUES (310,'Magdalena Milpas Altas');
INSERT INTO CAT_MUNICIPIO VALUES (311,'Santa María de Jesús');
INSERT INTO CAT_MUNICIPIO VALUES (312,'Ciudad Vieja');
INSERT INTO CAT_MUNICIPIO VALUES (313,'San Miguel Dueñas');
INSERT INTO CAT_MUNICIPIO VALUES (314,'San Juan Alotenango');
INSERT INTO CAT_MUNICIPIO VALUES (315,'San Antonio Aguas Calientes');
INSERT INTO CAT_MUNICIPIO VALUES (316,'Santa Catarina Barahona');
INSERT INTO CAT_MUNICIPIO VALUES (401,'Chimaltenango');
INSERT INTO CAT_MUNICIPIO VALUES (402,'San José  Poaquíl');
INSERT INTO CAT_MUNICIPIO VALUES (403,'San Martín Jilotepeque');
INSERT INTO CAT_MUNICIPIO VALUES (404,'Comalapa');
INSERT INTO CAT_MUNICIPIO VALUES (405,'Santa Apolonia');
INSERT INTO CAT_MUNICIPIO VALUES (406,'Tecpán Guatemala');
INSERT INTO CAT_MUNICIPIO VALUES (407,'Patzún ');
INSERT INTO CAT_MUNICIPIO VALUES (408,'San Miguel Pochuta');
INSERT INTO CAT_MUNICIPIO VALUES (409,'Patzicía');
INSERT INTO CAT_MUNICIPIO VALUES (410,'Santa Cruz Balanyá');
INSERT INTO CAT_MUNICIPIO VALUES (411,'Acatenango');
INSERT INTO CAT_MUNICIPIO VALUES (412,'Yepocapa');
INSERT INTO CAT_MUNICIPIO VALUES (413,'San Andrés Itzapa');
INSERT INTO CAT_MUNICIPIO VALUES (414,'Parramos');
INSERT INTO CAT_MUNICIPIO VALUES (415,'Zaragoza');
INSERT INTO CAT_MUNICIPIO VALUES (416,'El Tejar');
INSERT INTO CAT_MUNICIPIO VALUES (501,'Escuintla');
INSERT INTO CAT_MUNICIPIO VALUES (502,'Santa Lucía Cotzumalguapa');
INSERT INTO CAT_MUNICIPIO VALUES (503,'La Democracia');
INSERT INTO CAT_MUNICIPIO VALUES (504,'Siquinalá');
INSERT INTO CAT_MUNICIPIO VALUES (505,'Masagua');
INSERT INTO CAT_MUNICIPIO VALUES (506,'Tiquisate');
INSERT INTO CAT_MUNICIPIO VALUES (507,'La Gomera');
INSERT INTO CAT_MUNICIPIO VALUES (508,'Guanagazapa');
INSERT INTO CAT_MUNICIPIO VALUES (509,'San José');
INSERT INTO CAT_MUNICIPIO VALUES (510,'Iztapa');
INSERT INTO CAT_MUNICIPIO VALUES (511,'Palín');
INSERT INTO CAT_MUNICIPIO VALUES (512,'San Vicente Pacaya');
INSERT INTO CAT_MUNICIPIO VALUES (513,'Nueva Concepción');
INSERT INTO CAT_MUNICIPIO VALUES (514,'Sipacate');
INSERT INTO CAT_MUNICIPIO VALUES (601,'Cuilapa');
INSERT INTO CAT_MUNICIPIO VALUES (602,'Barberena');
INSERT INTO CAT_MUNICIPIO VALUES (603,'Santa Rosa de Lima');
INSERT INTO CAT_MUNICIPIO VALUES (604,'Casillas');
INSERT INTO CAT_MUNICIPIO VALUES (605,'San Rafael las Flores');
INSERT INTO CAT_MUNICIPIO VALUES (606,'Oratorio');
INSERT INTO CAT_MUNICIPIO VALUES (607,'San Juan Tecuaco');
INSERT INTO CAT_MUNICIPIO VALUES (608,'Chiquimulilla');
INSERT INTO CAT_MUNICIPIO VALUES (609,'Taxisco');
INSERT INTO CAT_MUNICIPIO VALUES (610,'Santa María Ixhuatán');
INSERT INTO CAT_MUNICIPIO VALUES (611,'Guazacapán');
INSERT INTO CAT_MUNICIPIO VALUES (612,'Santa Cruz el Naranjo');
INSERT INTO CAT_MUNICIPIO VALUES (613,'Pueblo Nuevo Viñas');
INSERT INTO CAT_MUNICIPIO VALUES (614,'Nueva Santa Rosa');
INSERT INTO CAT_MUNICIPIO VALUES (701,'Sololá');
INSERT INTO CAT_MUNICIPIO VALUES (702,'San José Chacayá');
INSERT INTO CAT_MUNICIPIO VALUES (703,'Santa María Visitación');
INSERT INTO CAT_MUNICIPIO VALUES (704,'Santa Lucía Utatlán');
INSERT INTO CAT_MUNICIPIO VALUES (705,'Nahualá');
INSERT INTO CAT_MUNICIPIO VALUES (706,'Santa Catarina Ixtahuacán');
INSERT INTO CAT_MUNICIPIO VALUES (707,'Santa Clara la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (708,'Concepción');
INSERT INTO CAT_MUNICIPIO VALUES (709,'San Andrés Semetabaj');
INSERT INTO CAT_MUNICIPIO VALUES (710,'Panajachel');
INSERT INTO CAT_MUNICIPIO VALUES (711,'Santa Catarina Palopó');
INSERT INTO CAT_MUNICIPIO VALUES (712,'San Antonio Palopó');
INSERT INTO CAT_MUNICIPIO VALUES (713,'San Lucas Tolimán');
INSERT INTO CAT_MUNICIPIO VALUES (714,'Santa Cruz la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (715,'San Pablo la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (716,'San Marcos la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (717,'San Juan la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (718,'San Pedro la Laguna');
INSERT INTO CAT_MUNICIPIO VALUES (719,'Santiago Atitlán');
INSERT INTO CAT_MUNICIPIO VALUES (801,'Totonicapán');
INSERT INTO CAT_MUNICIPIO VALUES (802,'San Cristóbal Totonicapán');
INSERT INTO CAT_MUNICIPIO VALUES (803,'San Francisco el Alto');
INSERT INTO CAT_MUNICIPIO VALUES (804,'San Andrés Xecul');
INSERT INTO CAT_MUNICIPIO VALUES (805,'Momostenango');
INSERT INTO CAT_MUNICIPIO VALUES (806,'Santa María Chiquimula');
INSERT INTO CAT_MUNICIPIO VALUES (807,'Santa Lucía la Reforma');
INSERT INTO CAT_MUNICIPIO VALUES (808,'San Bartolo Aguas Calientes');
INSERT INTO CAT_MUNICIPIO VALUES (901,'Quetzaltenango');
INSERT INTO CAT_MUNICIPIO VALUES (902,'Salcajá');
INSERT INTO CAT_MUNICIPIO VALUES (903,'Olintepeque');
INSERT INTO CAT_MUNICIPIO VALUES (904,'San Carlos Sija');
INSERT INTO CAT_MUNICIPIO VALUES (905,'Sibilia');
INSERT INTO CAT_MUNICIPIO VALUES (906,'Cabricán');
INSERT INTO CAT_MUNICIPIO VALUES (907,'Cajolá');
INSERT INTO CAT_MUNICIPIO VALUES (908,'San Miguel Siguilá');
INSERT INTO CAT_MUNICIPIO VALUES (909,'San Juan Ostuncalco');
INSERT INTO CAT_MUNICIPIO VALUES (910,'San Mateo');
INSERT INTO CAT_MUNICIPIO VALUES (911,'Concepción Chiquirichapa');
INSERT INTO CAT_MUNICIPIO VALUES (912,'San Martín Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (913,'Almolonga');
INSERT INTO CAT_MUNICIPIO VALUES (914,'Cantel');
INSERT INTO CAT_MUNICIPIO VALUES (915,'Huitán');
INSERT INTO CAT_MUNICIPIO VALUES (916,'Zunil');
INSERT INTO CAT_MUNICIPIO VALUES (917,'Colomba');
INSERT INTO CAT_MUNICIPIO VALUES (918,'San Francisco la Unión');
INSERT INTO CAT_MUNICIPIO VALUES (919,'El Palmar');
INSERT INTO CAT_MUNICIPIO VALUES (920,'Coatepeque');
INSERT INTO CAT_MUNICIPIO VALUES (921,'Génova');
INSERT INTO CAT_MUNICIPIO VALUES (922,'Flores Costa Cuca ');
INSERT INTO CAT_MUNICIPIO VALUES (923,'La Esperanza');
INSERT INTO CAT_MUNICIPIO VALUES (924,'Palestina de los Altos');
INSERT INTO CAT_MUNICIPIO VALUES (1001,'Mazatenango');
INSERT INTO CAT_MUNICIPIO VALUES (1002,'Cuyotenango');
INSERT INTO CAT_MUNICIPIO VALUES (1003,'San Francisco Zapotitlán');
INSERT INTO CAT_MUNICIPIO VALUES (1004,'San Bernardino');
INSERT INTO CAT_MUNICIPIO VALUES (1005,'San José el Ídolo');
INSERT INTO CAT_MUNICIPIO VALUES (1006,'Santo Domingo Suchitepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (1007,'San Lorenzo');
INSERT INTO CAT_MUNICIPIO VALUES (1008,'Samayac');
INSERT INTO CAT_MUNICIPIO VALUES (1009,'San Pablo Jocopilas');
INSERT INTO CAT_MUNICIPIO VALUES (1010,'San Antonio Suchitepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (1011,'San Miguel Panán');
INSERT INTO CAT_MUNICIPIO VALUES (1012,'San Gabriel ');
INSERT INTO CAT_MUNICIPIO VALUES (1013,'Chicacao');
INSERT INTO CAT_MUNICIPIO VALUES (1014,'Patulul');
INSERT INTO CAT_MUNICIPIO VALUES (1015,'Santa Bárbara');
INSERT INTO CAT_MUNICIPIO VALUES (1016,'San Juan Bautista');
INSERT INTO CAT_MUNICIPIO VALUES (1017,'Santo Tomas la Unión');
INSERT INTO CAT_MUNICIPIO VALUES (1018,'Zunilito');
INSERT INTO CAT_MUNICIPIO VALUES (1019,'Pueblo Nuevo');
INSERT INTO CAT_MUNICIPIO VALUES (1020,'Río Bravo');
INSERT INTO CAT_MUNICIPIO VALUES (1021,'San José La Máquina');
INSERT INTO CAT_MUNICIPIO VALUES (1101,'Retalhuleu');
INSERT INTO CAT_MUNICIPIO VALUES (1102,'San Sebastián');
INSERT INTO CAT_MUNICIPIO VALUES (1103,'Santa Cruz Muluá');
INSERT INTO CAT_MUNICIPIO VALUES (1104,'San Martín Zapotitlán');
INSERT INTO CAT_MUNICIPIO VALUES (1105,'San Felipe Retalhuleu');
INSERT INTO CAT_MUNICIPIO VALUES (1106,'San Andrés Villa Seca');
INSERT INTO CAT_MUNICIPIO VALUES (1107,'Champerico');
INSERT INTO CAT_MUNICIPIO VALUES (1108,'Nuevo San Carlos');
INSERT INTO CAT_MUNICIPIO VALUES (1109,'El Asintal');
INSERT INTO CAT_MUNICIPIO VALUES (1201,'San Marcos');
INSERT INTO CAT_MUNICIPIO VALUES (1202,'San Pedro Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (1203,'San Antonio Sacatepéquez');
INSERT INTO CAT_MUNICIPIO VALUES (1204,'Comitancillo');
INSERT INTO CAT_MUNICIPIO VALUES (1205,'San Miguel Ixtahuacán');
INSERT INTO CAT_MUNICIPIO VALUES (1206,'Concepción Tutuapa');
INSERT INTO CAT_MUNICIPIO VALUES (1207,'Tacaná ');
INSERT INTO CAT_MUNICIPIO VALUES (1208,'Sibinal');
INSERT INTO CAT_MUNICIPIO VALUES (1209,'Tajumulco ');
INSERT INTO CAT_MUNICIPIO VALUES (1210,'Tejutla');
INSERT INTO CAT_MUNICIPIO VALUES (1211,'San Rafael Pie de la Cuesta');
INSERT INTO CAT_MUNICIPIO VALUES (1212,'Nuevo Progreso');
INSERT INTO CAT_MUNICIPIO VALUES (1213,'El Tumbador');
INSERT INTO CAT_MUNICIPIO VALUES (1214,'El Rodeo');
INSERT INTO CAT_MUNICIPIO VALUES (1215,'Malacatán');
INSERT INTO CAT_MUNICIPIO VALUES (1216,'Catarina');
INSERT INTO CAT_MUNICIPIO VALUES (1217,'Ayutla ');
INSERT INTO CAT_MUNICIPIO VALUES (1218,'Ocós');
INSERT INTO CAT_MUNICIPIO VALUES (1219,'San Pablo');
INSERT INTO CAT_MUNICIPIO VALUES (1220,'El Quetzal ');
INSERT INTO CAT_MUNICIPIO VALUES (1221,'La Reforma');
INSERT INTO CAT_MUNICIPIO VALUES (1222,'Pajapita');
INSERT INTO CAT_MUNICIPIO VALUES (1223,'Ixchiguán');
INSERT INTO CAT_MUNICIPIO VALUES (1224,'San José Ojetenam');
INSERT INTO CAT_MUNICIPIO VALUES (1225,'San Cristóbal Cucho');
INSERT INTO CAT_MUNICIPIO VALUES (1226,'Sipacapa');
INSERT INTO CAT_MUNICIPIO VALUES (1227,'Esquipulas Palo Gordo');
INSERT INTO CAT_MUNICIPIO VALUES (1228,'Río Blanco');
INSERT INTO CAT_MUNICIPIO VALUES (1229,'San Lorenzo');
INSERT INTO CAT_MUNICIPIO VALUES (1230,'La Blanca');
INSERT INTO CAT_MUNICIPIO VALUES (1301,'Huehuetenango');
INSERT INTO CAT_MUNICIPIO VALUES (1302,'Chiantla');
INSERT INTO CAT_MUNICIPIO VALUES (1303,'Malacatancito');
INSERT INTO CAT_MUNICIPIO VALUES (1304,'Cuilco');
INSERT INTO CAT_MUNICIPIO VALUES (1305,'Nentón');
INSERT INTO CAT_MUNICIPIO VALUES (1306,'San Pedro Necta');
INSERT INTO CAT_MUNICIPIO VALUES (1307,'Jacaltenango');
INSERT INTO CAT_MUNICIPIO VALUES (1308,'San Pedro Soloma');
INSERT INTO CAT_MUNICIPIO VALUES (1309,'San Ildefonso Ixtahuacán');
INSERT INTO CAT_MUNICIPIO VALUES (1310,'Santa Bárbara');
INSERT INTO CAT_MUNICIPIO VALUES (1311,'La Libertad');
INSERT INTO CAT_MUNICIPIO VALUES (1312,'La Democracia');
INSERT INTO CAT_MUNICIPIO VALUES (1313,'San Miguel Acatán');
INSERT INTO CAT_MUNICIPIO VALUES (1314,'San Rafael La Independencia');
INSERT INTO CAT_MUNICIPIO VALUES (1315,'Todos Santos Cuchumatán');
INSERT INTO CAT_MUNICIPIO VALUES (1316,'San Juan Atitán');
INSERT INTO CAT_MUNICIPIO VALUES (1317,'Santa Eulalia');
INSERT INTO CAT_MUNICIPIO VALUES (1318,'San Mateo Ixtatán');
INSERT INTO CAT_MUNICIPIO VALUES (1319,'Colotenango');
INSERT INTO CAT_MUNICIPIO VALUES (1320,'San Sebastián Huehuetenango');
INSERT INTO CAT_MUNICIPIO VALUES (1321,'Tectitán ');
INSERT INTO CAT_MUNICIPIO VALUES (1322,'Concepción Huista');
INSERT INTO CAT_MUNICIPIO VALUES (1323,'San Juan Ixcoy');
INSERT INTO CAT_MUNICIPIO VALUES (1324,'San Antonio Huista');
INSERT INTO CAT_MUNICIPIO VALUES (1325,'San Sebastián Coatán');
INSERT INTO CAT_MUNICIPIO VALUES (1326,'Barrillas');
INSERT INTO CAT_MUNICIPIO VALUES (1327,'Aguacatán');
INSERT INTO CAT_MUNICIPIO VALUES (1328,'San Rafael Petzal');
INSERT INTO CAT_MUNICIPIO VALUES (1329,'San Gaspar Ixchil');
INSERT INTO CAT_MUNICIPIO VALUES (1330,'Santiago Chimaltenango');
INSERT INTO CAT_MUNICIPIO VALUES (1331,'Santa Ana Huista');
INSERT INTO CAT_MUNICIPIO VALUES (1332,'Unión Cantinil');
INSERT INTO CAT_MUNICIPIO VALUES (1333,'Petatán');
INSERT INTO CAT_MUNICIPIO VALUES (1401,'Santa Cruz del Quiché');
INSERT INTO CAT_MUNICIPIO VALUES (1402,'Chiché');
INSERT INTO CAT_MUNICIPIO VALUES (1403,'Chinique');
INSERT INTO CAT_MUNICIPIO VALUES (1404,'Zacualpa');
INSERT INTO CAT_MUNICIPIO VALUES (1405,'Chajul');
INSERT INTO CAT_MUNICIPIO VALUES (1406,'Chichicastenango');
INSERT INTO CAT_MUNICIPIO VALUES (1407,'Patzité');
INSERT INTO CAT_MUNICIPIO VALUES (1408,'San Antonio Ilotenango');
INSERT INTO CAT_MUNICIPIO VALUES (1409,'San Pedro Jocopilas');
INSERT INTO CAT_MUNICIPIO VALUES (1410,'Cunén');
INSERT INTO CAT_MUNICIPIO VALUES (1411,'San Juan Cotzal');
INSERT INTO CAT_MUNICIPIO VALUES (1412,'Joyabaj');
INSERT INTO CAT_MUNICIPIO VALUES (1413,'Santa María Nebaj');
INSERT INTO CAT_MUNICIPIO VALUES (1414,'San Andrés Sajcabajá');
INSERT INTO CAT_MUNICIPIO VALUES (1415,'San Miguel Uspantán');
INSERT INTO CAT_MUNICIPIO VALUES (1416,'Sacapulas');
INSERT INTO CAT_MUNICIPIO VALUES (1417,'San Bartolomé Jocotenango');
INSERT INTO CAT_MUNICIPIO VALUES (1418,'Canillá');
INSERT INTO CAT_MUNICIPIO VALUES (1419,'Chicamán');
INSERT INTO CAT_MUNICIPIO VALUES (1420,'Ixcán');
INSERT INTO CAT_MUNICIPIO VALUES (1421,'Pachalum');
INSERT INTO CAT_MUNICIPIO VALUES (1501,'Salamá');
INSERT INTO CAT_MUNICIPIO VALUES (1502,'San Miguel Chicaj');
INSERT INTO CAT_MUNICIPIO VALUES (1503,'Rabinal');
INSERT INTO CAT_MUNICIPIO VALUES (1504,'Cubulco');
INSERT INTO CAT_MUNICIPIO VALUES (1505,'Granados');
INSERT INTO CAT_MUNICIPIO VALUES (1506,'El Chol');
INSERT INTO CAT_MUNICIPIO VALUES (1507,'San Jerónimo');
INSERT INTO CAT_MUNICIPIO VALUES (1508,'Purulhá');
INSERT INTO CAT_MUNICIPIO VALUES (1601,'Cobán');
INSERT INTO CAT_MUNICIPIO VALUES (1602,'Santa Cruz Verapaz');
INSERT INTO CAT_MUNICIPIO VALUES (1603,'San Cristóbal Verapaz');
INSERT INTO CAT_MUNICIPIO VALUES (1604,'Tactic');
INSERT INTO CAT_MUNICIPIO VALUES (1605,'Tamahú');
INSERT INTO CAT_MUNICIPIO VALUES (1606,'Tucurú');
INSERT INTO CAT_MUNICIPIO VALUES (1607,'Panzós');
INSERT INTO CAT_MUNICIPIO VALUES (1608,'Senahú');
INSERT INTO CAT_MUNICIPIO VALUES (1609,'San Pedro Carchá');
INSERT INTO CAT_MUNICIPIO VALUES (1610,'San Juan Chamelco');
INSERT INTO CAT_MUNICIPIO VALUES (1611,'Lanquín');
INSERT INTO CAT_MUNICIPIO VALUES (1612,'Cahabón');
INSERT INTO CAT_MUNICIPIO VALUES (1613,'Chisec');
INSERT INTO CAT_MUNICIPIO VALUES (1614,'Chahal');
INSERT INTO CAT_MUNICIPIO VALUES (1615,'Fray Bartolomé de las Casas');
INSERT INTO CAT_MUNICIPIO VALUES (1616,'Santa Catarina La Tinta');
INSERT INTO CAT_MUNICIPIO VALUES (1617,'Raxruhá');
INSERT INTO CAT_MUNICIPIO VALUES (1701,'Flores');
INSERT INTO CAT_MUNICIPIO VALUES (1702,'San José');
INSERT INTO CAT_MUNICIPIO VALUES (1703,'San Benito');
INSERT INTO CAT_MUNICIPIO VALUES (1704,'San Andrés');
INSERT INTO CAT_MUNICIPIO VALUES (1705,'La Libertad');
INSERT INTO CAT_MUNICIPIO VALUES (1706,'San Francisco');
INSERT INTO CAT_MUNICIPIO VALUES (1707,'Santa Ana');
INSERT INTO CAT_MUNICIPIO VALUES (1708,'Dolores');
INSERT INTO CAT_MUNICIPIO VALUES (1709,'San Luis');
INSERT INTO CAT_MUNICIPIO VALUES (1710,'Sayaxché');
INSERT INTO CAT_MUNICIPIO VALUES (1711,'Melchor de Mencos');
INSERT INTO CAT_MUNICIPIO VALUES (1712,'Poptún');
INSERT INTO CAT_MUNICIPIO VALUES (1713,'Las Cruces');
INSERT INTO CAT_MUNICIPIO VALUES (1714,'El Chal');
INSERT INTO CAT_MUNICIPIO VALUES (1801,'Puerto Barrios');
INSERT INTO CAT_MUNICIPIO VALUES (1802,'Livingston');
INSERT INTO CAT_MUNICIPIO VALUES (1803,'El Estor');
INSERT INTO CAT_MUNICIPIO VALUES (1804,'Morales');
INSERT INTO CAT_MUNICIPIO VALUES (1805,'Los Amates');
INSERT INTO CAT_MUNICIPIO VALUES (1901,'Zacapa');
INSERT INTO CAT_MUNICIPIO VALUES (1902,'Estanzuela');
INSERT INTO CAT_MUNICIPIO VALUES (1903,'Río Hondo');
INSERT INTO CAT_MUNICIPIO VALUES (1904,'Gualán');
INSERT INTO CAT_MUNICIPIO VALUES (1905,'Teculután');
INSERT INTO CAT_MUNICIPIO VALUES (1906,'Usumatlán');
INSERT INTO CAT_MUNICIPIO VALUES (1907,'Cabañas ');
INSERT INTO CAT_MUNICIPIO VALUES (1908,'San Diego');
INSERT INTO CAT_MUNICIPIO VALUES (1909,'La Unión');
INSERT INTO CAT_MUNICIPIO VALUES (1910,'Huité');
INSERT INTO CAT_MUNICIPIO VALUES (1911,'San Jorge');
INSERT INTO CAT_MUNICIPIO VALUES (2001,'Chiquimula');
INSERT INTO CAT_MUNICIPIO VALUES (2002,'San José la Arada');
INSERT INTO CAT_MUNICIPIO VALUES (2003,'San Juan Ermita');
INSERT INTO CAT_MUNICIPIO VALUES (2004,'Jocotán');
INSERT INTO CAT_MUNICIPIO VALUES (2005,'Camotán');
INSERT INTO CAT_MUNICIPIO VALUES (2006,'Olopa');
INSERT INTO CAT_MUNICIPIO VALUES (2007,'Esquipulas');
INSERT INTO CAT_MUNICIPIO VALUES (2008,'Concepción las Minas');
INSERT INTO CAT_MUNICIPIO VALUES (2009,'Quezaltepeque');
INSERT INTO CAT_MUNICIPIO VALUES (2010,'San Jacinto ');
INSERT INTO CAT_MUNICIPIO VALUES (2011,'Ipala');
INSERT INTO CAT_MUNICIPIO VALUES (2101,'Jalapa');
INSERT INTO CAT_MUNICIPIO VALUES (2102,'San Pedro Pinula');
INSERT INTO CAT_MUNICIPIO VALUES (2103,'San Luis Jilotepeque');
INSERT INTO CAT_MUNICIPIO VALUES (2104,'San Manuel Chaparrón');
INSERT INTO CAT_MUNICIPIO VALUES (2105,'San Carlos Alzatate');
INSERT INTO CAT_MUNICIPIO VALUES (2106,'Monjas');
INSERT INTO CAT_MUNICIPIO VALUES (2107,'Mataquescuintla');
INSERT INTO CAT_MUNICIPIO VALUES (2201,'Jutiapa');
INSERT INTO CAT_MUNICIPIO VALUES (2202,'El Progreso');
INSERT INTO CAT_MUNICIPIO VALUES (2203,'Santa Catarina Mita');
INSERT INTO CAT_MUNICIPIO VALUES (2204,'Agua Blanca');
INSERT INTO CAT_MUNICIPIO VALUES (2205,'Asunción Mita');
INSERT INTO CAT_MUNICIPIO VALUES (2206,'Yupiltepeque');
INSERT INTO CAT_MUNICIPIO VALUES (2207,'Atescatempa');
INSERT INTO CAT_MUNICIPIO VALUES (2208,'Jerez ');
INSERT INTO CAT_MUNICIPIO VALUES (2209,'El Adelanto');
INSERT INTO CAT_MUNICIPIO VALUES (2210,'Zapotitlán');
INSERT INTO CAT_MUNICIPIO VALUES (2211,'Comapa');
INSERT INTO CAT_MUNICIPIO VALUES (2212,'Jalpatagua');
INSERT INTO CAT_MUNICIPIO VALUES (2213,'Conguaco');
INSERT INTO CAT_MUNICIPIO VALUES (2214,'Moyuta');
INSERT INTO CAT_MUNICIPIO VALUES (2215,'Pasaco');
INSERT INTO CAT_MUNICIPIO VALUES (2216,'San José Acatempa');
INSERT INTO CAT_MUNICIPIO VALUES (2217,'Quesada');


-- CAT_ZONA
INSERT INTO CAT_ZONA VALUES (0,'CERO');
INSERT INTO CAT_ZONA VALUES (1,'UNA');
INSERT INTO CAT_ZONA VALUES (2,'DOS');
INSERT INTO CAT_ZONA VALUES (3,'TRES');
INSERT INTO CAT_ZONA VALUES (4,'CUATRO');
INSERT INTO CAT_ZONA VALUES (5,'CINCO');
INSERT INTO CAT_ZONA VALUES (6,'SEIS');
INSERT INTO CAT_ZONA VALUES (7,'SIETE');
INSERT INTO CAT_ZONA VALUES (8,'OCHO');
INSERT INTO CAT_ZONA VALUES (9,'NUEVE');
INSERT INTO CAT_ZONA VALUES (10,'DIEZ');
INSERT INTO CAT_ZONA VALUES (11,'ONCE');
INSERT INTO CAT_ZONA VALUES (12,'DOCE');
INSERT INTO CAT_ZONA VALUES (13,'TRECE');
INSERT INTO CAT_ZONA VALUES (14,'CATORCE');
INSERT INTO CAT_ZONA VALUES (15,'QUINCE');
INSERT INTO CAT_ZONA VALUES (16,'DIECISEIS');
INSERT INTO CAT_ZONA VALUES (17,'DIECISIETE');
INSERT INTO CAT_ZONA VALUES (18,'DIECIOCHO');
INSERT INTO CAT_ZONA VALUES (19,'DIECINUEVE');
INSERT INTO CAT_ZONA VALUES (21,'VEINTIUNO');
INSERT INTO CAT_ZONA VALUES (24,'VEINTICUATRO');
INSERT INTO CAT_ZONA VALUES (25,'VEINTICINCO');
INSERT INTO CAT_ZONA VALUES (99,'SIN REGISTRO');

--CAT_GENERO
INSERT INTO CAT_ZONA VALUES (1,'Hombre');
INSERT INTO CAT_ZONA VALUES (2,'Mujer');
INSERT INTO CAT_ZONA VALUES (9,'Ignorado');

--CAT_G_EDAD_80_MAS
INSERT INTO CAT_G_EDAD_80_MAS VALUES (1,'Menor de 15');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (2,'15-19');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (3,'20-24');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (4,'25-29');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (5,'30-34');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (6,'35-39');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (7,'40-44');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (8,'45-49');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (9,'50-54');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (10,'55-59');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (11,'60-64');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (12,'65-69');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (13,'70-74');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (14,'75-80');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (15,'80 y más');
INSERT INTO CAT_G_EDAD_80_MAS VALUES (16,'Ignorado');

-- CAT_G_EDAD_60_MAS
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (1,'Menor de 15');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (2,'15-19');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (3,'20-24');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (4,'25-29');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (5,'30-34');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (6,'35-39');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (7,'40-44');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (8,'45-49');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (9,'50-54');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (10,'55-59');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (11,'60 y más');
INSERT INTO  CAT_G_EDAD_60_MAS VALUES (12,'Ignorado');

--CAT_EDAD_QUINCENAL
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (1,'0 - 4');
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (2,'5 - 9');
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (3,'10 - 14');
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (4,'15 - 19');
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (5,'20 - 24'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (6,'25 - 29'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (7,'30 - 34'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (8,'35 - 39'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (9,'40 - 44'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (10,'45 - 49'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (11,'50 - 54'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (12,'55 - 59'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (13,'60 - 64'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (14,'65 - 69'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (15,'70 - 74'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (16,'75 - 79'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (17,'80 o más'); 
INSERT INTO  CAT_EDAD_QUINCENAL VALUES (18,'Ignorado'); 

--CAT_MAYOR_MENOR
INSERT INTO CAT_MAYOR_MENOR VALUES (1,'Mayor');
INSERT INTO CAT_MAYOR_MENOR VALUES (2,'Menor');
INSERT INTO CAT_MAYOR_MENOR VALUES (9,'Ignorado');

-- CAT_TIPO_VEHICULO

INSERT INTO CAT_TIPO_VEHICULO VALUES (1,'Automóvil');
INSERT INTO CAT_TIPO_VEHICULO VALUES (2,'Camioneta sport o blazer');
INSERT INTO CAT_TIPO_VEHICULO VALUES (3,'Pick up');
INSERT INTO CAT_TIPO_VEHICULO VALUES (4,'Motocicleta');
INSERT INTO CAT_TIPO_VEHICULO VALUES (5,'Camión');
INSERT INTO CAT_TIPO_VEHICULO VALUES (6,'Cabezal');
INSERT INTO CAT_TIPO_VEHICULO VALUES (7,'Bus extraurbano');
INSERT INTO CAT_TIPO_VEHICULO VALUES (8,'Jeep');
INSERT INTO CAT_TIPO_VEHICULO VALUES (9,'Microbús');
INSERT INTO CAT_TIPO_VEHICULO VALUES (10,'Taxi');
INSERT INTO CAT_TIPO_VEHICULO VALUES (11,'Panel');
INSERT INTO CAT_TIPO_VEHICULO VALUES (12,'Bus urbano');
INSERT INTO CAT_TIPO_VEHICULO VALUES (13,'Tractor');
INSERT INTO CAT_TIPO_VEHICULO VALUES (14,'Moto taxi');
INSERT INTO CAT_TIPO_VEHICULO VALUES (15,'Furgón');
INSERT INTO CAT_TIPO_VEHICULO VALUES (16,'Grúa');
INSERT INTO CAT_TIPO_VEHICULO VALUES (17,'Bus escolar');
INSERT INTO CAT_TIPO_VEHICULO VALUES (18,'Bicicleta');
INSERT INTO CAT_TIPO_VEHICULO VALUES (19,'Avioneta');
INSERT INTO CAT_TIPO_VEHICULO VALUES (20,'Montacargas');
INSERT INTO CAT_TIPO_VEHICULO VALUES (21,'Bus militar');
INSERT INTO CAT_TIPO_VEHICULO VALUES (22,'Cuatrimoto');
INSERT INTO CAT_TIPO_VEHICULO VALUES (23,'Furgoneta');
INSERT INTO CAT_TIPO_VEHICULO VALUES (99,'Ignorado');

-- CAT_MARCA_VEHICULO

INSERT INTO CAT_MODELO_VEHICULO VALUES (1,'DAMC');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2,'ACURA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (3,'ALFA-ROMEO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (4,'APACHE-AMMEX');
INSERT INTO CAT_MODELO_VEHICULO VALUES (5,'AUDI');
INSERT INTO CAT_MODELO_VEHICULO VALUES (6,'AMC-JEEP');
INSERT INTO CAT_MODELO_VEHICULO VALUES (8,'VOLKSWAGEN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (9,'DELTA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (10,'ASTON MARTIN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (13,'ADVENTURE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (14,'AUTOCAR');
INSERT INTO CAT_MODELO_VEHICULO VALUES (15,'AUSTIN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (16,'ALL AMERICAN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (17,'ABIR');
INSERT INTO CAT_MODELO_VEHICULO VALUES (18,'ASIA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (19,'AUTOBIANCHI');
INSERT INTO CAT_MODELO_VEHICULO VALUES (20,'TOYOTA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (21,'ASPT');
INSERT INTO CAT_MODELO_VEHICULO VALUES (23,'ARC');
INSERT INTO CAT_MODELO_VEHICULO VALUES (25,'DARGOSY');
INSERT INTO CAT_MODELO_VEHICULO VALUES (26,'ASTRA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (27,'ASIA SMITH');
INSERT INTO CAT_MODELO_VEHICULO VALUES (28,'TATA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (30,'AM GENERAL');
INSERT INTO CAT_MODELO_VEHICULO VALUES (31,'BUICK');
INSERT INTO CAT_MODELO_VEHICULO VALUES (32,'BMW');
INSERT INTO CAT_MODELO_VEHICULO VALUES (34,'BETA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (35,'BIMOTA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (36,'BOMBARDIER LTD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (38,'BULLDOG');
INSERT INTO CAT_MODELO_VEHICULO VALUES (39,'BAJAJ');
INSERT INTO CAT_MODELO_VEHICULO VALUES (40,'BENELLI');
INSERT INTO CAT_MODELO_VEHICULO VALUES (41,'BULTACO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (42,'BLUE BIRD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (43,'BROCKWAY');
INSERT INTO CAT_MODELO_VEHICULO VALUES (45,'BEDFORD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (46,'BOLES AERO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (48,'BUD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (50,'BRAE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (51,'BERTONE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (52,'CADILLAC');
INSERT INTO CAT_MODELO_VEHICULO VALUES (53,'CHECKER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (54,'CHEVROLET');
INSERT INTO CAT_MODELO_VEHICULO VALUES (55,'CHRYSLER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (56,'CAGIVA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (58,'CARL HEALD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (59,'COSMO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (62,'CITROEN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (64,'COLT');
INSERT INTO CAT_MODELO_VEHICULO VALUES (66,'CROWN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (67,'CRANE CARRIER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (69,'CRAN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (71,'AMG');
INSERT INTO CAT_MODELO_VEHICULO VALUES (72,'COMMER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (73,'AGRALE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (74,'CHALLENGER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (75,'CANTER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (76,'COACHMEN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (77,'CONSOLIDATE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (83,'CUSHMAN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (84,'CCC');
INSERT INTO CAT_MODELO_VEHICULO VALUES (87,'CHANGAN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (88,'CORVETTE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (90,'COOK');
INSERT INTO CAT_MODELO_VEHICULO VALUES (96,'DODGE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (99,'DATSUN');
INSERT INTO CAT_MODELO_VEHICULO VALUES (100,'DERBI');
INSERT INTO CAT_MODELO_VEHICULO VALUES (102,'DUCATI');
INSERT INTO CAT_MODELO_VEHICULO VALUES (103,'DAIHATSU');
INSERT INTO CAT_MODELO_VEHICULO VALUES (112,'DAEWOO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (113,'DIAMOND');
INSERT INTO CAT_MODELO_VEHICULO VALUES (114,'FORD');
INSERT INTO CAT_MODELO_VEHICULO VALUES (115,'FIAT');
INSERT INTO CAT_MODELO_VEHICULO VALUES (116,'DAIMLER BENZ');
INSERT INTO CAT_MODELO_VEHICULO VALUES (123,'DACIA');
INSERT INTO CAT_MODELO_VEHICULO VALUES (145,'DKW');
INSERT INTO CAT_MODELO_VEHICULO VALUES (158,'DUNE BUGGIE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (163,'DONG FENG');
INSERT INTO CAT_MODELO_VEHICULO VALUES (168,'DORSEY');
INSERT INTO CAT_MODELO_VEHICULO VALUES (172,'EZRIDER');
INSERT INTO CAT_MODELO_VEHICULO VALUES (173,'EAGLE');
INSERT INTO CAT_MODELO_VEHICULO VALUES (190,'EBRO');
INSERT INTO CAT_MODELO_VEHICULO VALUES (999,'NO DEFINIDA');

-- CAT_COLOR_VEHICULO
INSERT INTO CAT_COLOR_VEHICULO VALUES (1,'Rojo');
INSERT INTO CAT_COLOR_VEHICULO VALUES (2,'Blanco');
INSERT INTO CAT_COLOR_VEHICULO VALUES (3,'Azul');
INSERT INTO CAT_COLOR_VEHICULO VALUES (4,'Gris');
INSERT INTO CAT_COLOR_VEHICULO VALUES (5,'Negro');
INSERT INTO CAT_COLOR_VEHICULO VALUES (6,'Verde');
INSERT INTO CAT_COLOR_VEHICULO VALUES (7,'Amarillo');
INSERT INTO CAT_COLOR_VEHICULO VALUES (8,'Celeste');
INSERT INTO CAT_COLOR_VEHICULO VALUES (9,'Corinto');
INSERT INTO CAT_COLOR_VEHICULO VALUES (10,'Café');
INSERT INTO CAT_COLOR_VEHICULO VALUES (11,'Beige');
INSERT INTO CAT_COLOR_VEHICULO VALUES (12,'Turquesa');
INSERT INTO CAT_COLOR_VEHICULO VALUES (13,'Marfil');
INSERT INTO CAT_COLOR_VEHICULO VALUES (14,'Anaranjado');
INSERT INTO CAT_COLOR_VEHICULO VALUES (15,'Morado');
INSERT INTO CAT_COLOR_VEHICULO VALUES (16,'Rosado');
INSERT INTO CAT_COLOR_VEHICULO VALUES (17,'Varios colores');
INSERT INTO CAT_COLOR_VEHICULO VALUES (99,'Ignorado');

-- CAT_MODELO_VEHICULO
INSERT INTO CAT_MODELO_VEHICULO VALUES (1977,'Modelo 1977');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1978,'Modelo 1978');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1979,'Modelo 1979');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1980,'Modelo 1980');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1981,'Modelo 1981');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1982,'Modelo 1982');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1983,'Modelo 1983');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1984,'Modelo 1984');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1985,'Modelo 1985');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1986,'Modelo 1986');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1987,'Modelo 1987');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1988,'Modelo 1988');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1989,'Modelo 1989');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1990,'Modelo 1990');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1991,'Modelo 1991');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1992,'Modelo 1992');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1993,'Modelo 1993');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1994,'Modelo 1994');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1995,'Modelo 1995');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1996,'Modelo 1996');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1997,'Modelo 1997');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1998,'Modelo 1998');
INSERT INTO CAT_MODELO_VEHICULO VALUES (1999,'Modelo 1999');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2000,'Modelo 2000');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2001,'Modelo 2001');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2002,'Modelo 2002');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2003,'Modelo 2003');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2004,'Modelo 2004');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2005,'Modelo 2005');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2006,'Modelo 2006');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2007,'Modelo 2007');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2008,'Modelo 2008');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2009,'Modelo 2009');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2010,'Modelo 2010');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2011,'Modelo 2011');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2012,'Modelo 2012');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2013,'Modelo 2013');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2014,'Modelo 2014');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2015,'Modelo 2015');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2016,'Modelo 2016');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2017,'Modelo 2017');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2018,'Modelo 2018');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2019,'Modelo 2019');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2020,'Modelo 2020');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2021,'Modelo 2021');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2022,'Modelo 2022');
INSERT INTO CAT_MODELO_VEHICULO VALUES (2023,'Modelo 2023');
INSERT INTO CAT_MODELO_VEHICULO VALUES (9999,'Modelo No Definido');

-- CAT_G_MODELO_VEHICULO
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (1,'1970-1979');
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (2,'1980-1989');
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (3,'1990-1999');
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (4,'2000-2009');
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (5,'2010-2019');
INSERT INTO CAT_G_MODELO_VEHICULO VALUES (99,'Ignorado');

-- CAT_TIPO_EVENTO
INSERT INTO CAT_TIPO_EVENTO VALUES (1,'Colisión');
INSERT INTO CAT_TIPO_EVENTO VALUES (2,'Choque');
INSERT INTO CAT_TIPO_EVENTO VALUES (3,'Vuelco');
INSERT INTO CAT_TIPO_EVENTO VALUES (4,'Caída');
INSERT INTO CAT_TIPO_EVENTO VALUES (5,'Atropello');
INSERT INTO CAT_TIPO_EVENTO VALUES (6,'Derrape');
INSERT INTO CAT_TIPO_EVENTO VALUES (7,'Embarranco');
INSERT INTO CAT_TIPO_EVENTO VALUES (8,'Encuneto');
INSERT INTO CAT_TIPO_EVENTO VALUES (99,'Ignorado');

-- CAT_FALLECIDO_LESIONADO
INSERT INTO CAT_FALLECIDO_LESIONADO VALUES (1,'Fallecido');
INSERT INTO CAT_FALLECIDO_LESIONADO VALUES (2,'Lesionado');

-- CAT_INTERNADO
INSERT INTO CAT_INTERNADO VALUES (1,'Internado');
INSERT INTO CAT_INTERNADO VALUES (2,'No Internado');
INSERT INTO CAT_INTERNADO VALUES (9,'Ignorado');

COMMIT;


------------------------------------------------------------
--TRIGGERS
------------------------------------------------------------

create or replace trigger TRG_TRANSACCION_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON TRANSACCION
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('TRANSACCION', :NEW.CORRELATIVO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('TRANSACCION', :OLD.CORRELATIVO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('TRANSACCION', :OLD.CORRELATIVO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;

------------   
create or replace trigger TRG_CAT_HORA_OCURRENCIA_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_HORA_OCURRENCIA
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_HORA_OCURRENCIA', :NEW.ID_HORA,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_HORA_OCURRENCIA', :OLD.ID_HORA,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_HORA_OCURRENCIA', :OLD.ID_HORA,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;

--

create or replace trigger TRG_CAT_G_HORA_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_G_HORA
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA', :NEW.ID_G_HORA,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA', :OLD.ID_G_HORA,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA', :OLD.ID_G_HORA,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_G_HORA_5_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_G_HORA_5
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA_5', :NEW.ID_G_HORA_5,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA_5', :OLD.ID_G_HORA_5,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_HORA_5', :OLD.ID_G_HORA_5,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_DEPARTAMENTO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_DEPARTAMENTO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_DEPARTAMENTO', :NEW.ID_DEPARTAMENTO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_DEPARTAMENTO', :OLD.ID_DEPARTAMENTO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_DEPARTAMENTO', :OLD.ID_DEPARTAMENTO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_MUNICIPIO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_MUNICIPIO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MUNICIPIO', :NEW.ID_MUNICIPIO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_MUNICIPIO', :OLD.ID_MUNICIPIO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MUNICIPIO', :OLD.ID_MUNICIPIO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_ZONA_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_ZONA
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_ZONA', :NEW.ID_ZONA,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_ZONA', :OLD.ID_ZONA,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_ZONA', :OLD.ID_ZONA,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_GENERO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_GENERO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_GENERO', :NEW.ID_GENERO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_GENERO', :OLD.ID_GENERO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_GENERO', :OLD.ID_GENERO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_EDAD_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_EDAD
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_EDAD', :NEW.ID_EDAD,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_EDAD', :OLD.ID_EDAD,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_EDAD', :OLD.ID_EDAD,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_G_EDAD_80_MAS_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_G_EDAD_80_MAS
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_80_MAS', :NEW.ID_G_EDAD_80_MAS,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_80_MAS', :OLD.ID_G_EDAD_80_MAS,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_80_MAS', :OLD.ID_G_EDAD_80_MAS,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_G_EDAD_60_MAS_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_G_EDAD_60_MAS
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_60_MAS', :NEW.ID_G_EDAD_60_MAS,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_60_MAS', :OLD.ID_G_EDAD_60_MAS,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_EDAD_60_MAS', :OLD.ID_G_EDAD_60_MAS,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_EDAD_QUINCENAL_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_EDAD_QUINCENAL
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_EDAD_QUINCENAL', :NEW.ID_EDAD_QUINCENAL,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_EDAD_QUINCENAL', :OLD.ID_EDAD_QUINCENAL,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_EDAD_QUINCENAL', :OLD.ID_EDAD_QUINCENAL,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_MAYOR_MENOR_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_MAYOR_MENOR
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MAYOR_MENOR', :NEW.ID_MAYOR_MENOR,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_MAYOR_MENOR', :OLD.ID_MAYOR_MENOR,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MAYOR_MENOR', :OLD.ID_MAYOR_MENOR,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_TIPO_VEHICULO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_TIPO_VEHICULO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_VEHICULO', :NEW.ID_TIPO_VEHICULO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_VEHICULO', :OLD.ID_TIPO_VEHICULO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_VEHICULO', :OLD.ID_TIPO_VEHICULO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_MARCA_VEHICULO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_MARCA_VEHICULO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MARCA_VEHICULO', :NEW.ID_MARCA_VEHICULO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_MARCA_VEHICULO', :OLD.ID_MARCA_VEHICULO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MARCA_VEHICULO', :OLD.ID_MARCA_VEHICULO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;

--

create or replace trigger TRG_CAT_COLOR_VEHICULO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_COLOR_VEHICULO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_COLOR_VEHICULO', :NEW.ID_COLOR_VEHICULO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_COLOR_VEHICULO', :OLD.ID_COLOR_VEHICULO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_COLOR_VEHICULO', :OLD.ID_COLOR_VEHICULO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_MODELO_VEHICULO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_MODELO_VEHICULO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MODELO_VEHICULO', :NEW.ID_MODELO_VEHICULO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_MODELO_VEHICULO', :OLD.ID_MODELO_VEHICULO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_MODELO_VEHICULO', :OLD.ID_MODELO_VEHICULO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_G_MODELO_VEHICULO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_G_MODELO_VEHICULO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_MODELO_VEHICULO', :NEW.ID_G_MODELO_VEHICULO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_G_MODELO_VEHICULO', :OLD.ID_G_MODELO_VEHICULO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_G_MODELO_VEHICULO', :OLD.ID_G_MODELO_VEHICULO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_TIPO_EVENTO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_TIPO_EVENTO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_EVENTO', :NEW.ID_TIPO_EVENTO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_EVENTO', :OLD.ID_TIPO_EVENTO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_TIPO_EVENTO', :OLD.ID_TIPO_EVENTO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_FALLECIDO_LESIONADO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_FALLECIDO_LESIONADO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_FALLECIDO_LESIONADO', :NEW.ID_FALLECIDO_LESIONADO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_FALLECIDO_LESIONADO', :OLD.ID_FALLECIDO_LESIONADO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_FALLECIDO_LESIONADO', :OLD.ID_FALLECIDO_LESIONADO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;
    
--

create or replace trigger TRG_CAT_INTERNADO_SINC
    BEFORE INSERT OR DELETE OR UPDATE
    ON CAT_INTERNADO
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            INSERT INTO WATERMARK VALUES ('CAT_INTERNADO', :NEW.ID_INTERNADO,
                'I', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF UPDATING THEN 
            INSERT INTO WATERMARK VALUES ('CAT_INTERNADO', :OLD.ID_INTERNADO,
                'U', SYSDATE, DEFAULT, SYSDATE);
        END IF;
        IF DELETING THEN
            INSERT INTO WATERMARK VALUES ('CAT_INTERNADO', :OLD.ID_INTERNADO,
                'D', SYSDATE, DEFAULT, SYSDATE);
        END IF;
    END;

--
GRANT SELECT ON TRANSACCION TO USR_STAGE;
GRANT SELECT ON CAT_HORA_OCURRENCIA TO USR_STAGE;
GRANT SELECT ON CAT_G_HORA TO USR_STAGE;
GRANT SELECT ON CAT_G_HORA_5 TO USR_STAGE;
GRANT SELECT ON CAT_DEPARTAMENTO TO USR_STAGE;
GRANT SELECT ON CAT_MUNICIPIO TO USR_STAGE;
GRANT SELECT ON CAT_ZONA TO USR_STAGE;
GRANT SELECT ON CAT_GENERO TO USR_STAGE;
GRANT SELECT ON CAT_EDAD TO USR_STAGE;
GRANT SELECT ON CAT_G_EDAD_80_MAS TO USR_STAGE;
GRANT SELECT ON CAT_G_EDAD_60_MAS TO USR_STAGE;
GRANT SELECT ON CAT_EDAD_QUINCENAL TO USR_STAGE;
GRANT SELECT ON CAT_MAYOR_MENOR TO USR_STAGE;
GRANT SELECT ON CAT_TIPO_VEHICULO TO USR_STAGE;
GRANT SELECT ON CAT_MARCA_VEHICULO TO USR_STAGE;
GRANT SELECT ON CAT_COLOR_VEHICULO TO USR_STAGE;
GRANT SELECT ON CAT_MODELO_VEHICULO TO USR_STAGE;
GRANT SELECT ON CAT_G_MODELO_VEHICULO TO USR_STAGE;
GRANT SELECT ON CAT_TIPO_EVENTO TO USR_STAGE;
GRANT SELECT ON CAT_FALLECIDO_LESIONADO TO USR_STAGE;
GRANT SELECT ON CAT_INTERNADO TO USR_STAGE;
GRANT SELECT ON WATERMARK TO USR_STAGE;



SELECT * FROM CAT_MAYOR_MENOR
SELECT * FROM CAT_ZONA
select * from transaccion

